#include <diagram_writer.h>

diagram_writer::diagram_writer(const QString &filename, editor *edit,
			       QWidget *parent)
{
  QFile qf;
  QString error = "";
  QTextStream qts;

  /*
  ** Write the data to the specified file.
  */

  saved = false;
  qf.setName(filename);

  if(!qf.open(IO_Truncate | IO_Translate | IO_WriteOnly))
    {
      error = "Unable to open " + filename + ".";
      goto error_label;
    }

  QApplication::setOverrideCursor(QCursor(Qt::WaitCursor));
  qts.setDevice(&qf);

  /*
  ** Include a warning message in the file.
  */

  qts << "Created by QtNQC. Please do not edit this file." << endl << endl;

  /*
  ** Now it gets interesting.
  */

  edit->writeToFile(qts, error);

  /*
  ** Set this only if the writes were successful.
  */

  if(parent != NULL && error.isEmpty())
    parent->setCaption("QtNQC " + QString(VERSION) + ": " + filename);

  QApplication::restoreOverrideCursor();

 error_label:

  if(!error.isEmpty())
    {
      if(parent != NULL)
	(void) QMessageBox::critical(parent, "Error", error,
				     QMessageBox::Ok | QMessageBox::Default,
				     0);
    }
  else
    saved = true;

  qf.close();
}

/*
** -- isSaved() --
*/

bool diagram_writer::isSaved(void)
{
  return saved;
}
